<h1>Users</h1>

<a href="<?php echo $this->url('sonuser-admin/default', array('action' => 'new'));?>" class="btn btn-primary">Novo</a>

<table class="table">
    <tr>
        <th>Id</th>
        <th>Nome</th>
        <th>Email</th>
        <th>Acão</th>
    </tr>
    
    <?php foreach($this->data as $entity): ?>
        <tr>
            <td><?php echo $entity->getId(); ?></td>
            <td><?php echo $entity->getNome(); ?></td>
            <td><?php echo $entity->getEmail(); ?></td>
            <td></td>
        </tr>    
    <?php endforeach;  ?>
</table>