<h1>Users</h1>

<a href="<?php echo $this->url('sonuser-admin/default', array('action' => 'new'));?>" class="btn btn-primary">Novo</a>
<br>
<table class="table">
    <tr>
        <th>Id</th>
        <th>Nome</th>
        <th>Email</th>
        <th>Acão</th>
    </tr>
    
    <?php foreach($this->data as $entity): ?>
        <tr>
            <td><?php echo $entity->getId(); ?></td>
            <td><?php echo $entity->getNome(); ?></td>
            <td><?php echo $entity->getEmail(); ?></td>
            <td>
                <a class="btn-sm btn-primary" href="<?php echo $this->url('sonuser-admin/default',array('action'=>'edit', 'id'=>$entity->getId()));?>">Editar</a>
                <a class="btn-sm btn-danger" href="<?php echo $this->url('sonuser-admin/default',array('action'=>'delete', 'id'=>$entity->getId()));?>">Deletar</a>
            </td>
        </tr>    
    <?php endforeach;  ?>
</table>

<?php echo $this->paginationControl($this->data, 'Sliding', 'partials/paginator'); ?>