<?php
$urlPattern = $_SERVER['REQUEST_URI'];

$formatUrl = function ($page) use ($urlPattern){
    if(!preg_match('/page/', $urlPattern)){
            return $urlPattern.'/page/'.(int)$page;
    }
    else{
        return preg_replace('@/page/\d@', '/page/'.(int)$page, $urlPattern);
    }
};

if($this->pageCount): ?>

<nav>
    <ul class="pagination">
        <?php if(isset($this->previous)): ?>
        <li><a href="<?php echo $formatUrl($this->previous); ?>">Anterior</a></li>
        
        <?php else: ?>
            <li class="disabled"><a href="#">Anterior</a></li>
        <?php  endif; ?>
            
      <?php foreach($this->pagesInRange as $page): ?>
            <?php if($page != $this->current): ?>
            
            <li>
                <a href="<?php echo $formatUrl($page); ?>"><?php echo $page; ?></a>
            </li>
            
            <?php else: ?>
            
            <li class="active">
                <a href="<?php echo $formatUrl($page); ?>"><?php echo $page; ?></a>
            </li>
            
            <?php endif; ?>
            <?php   endforeach; ?>
            
            <?php if(isset($this->next)): ?>
                <li><a href="<?php echo $formatUrl($this->next); ?>">Próximo</a></li>
            <?php else: ?>
                <li class="disabled"><a href="#">Próximo</a></li>
            <?php endif; ?>
    </ul>
</nav>

<?php endif; ?>


